### ISSUE TITLE
Feature Request: Tesla Overlay

### ISSUE THREAD

**Issue by NWPlayer123** [averne/Turnips#12]
It'd be nice to have this as an overlay on the actual game. See:
https://github.com/WerWolv/libtesla
https://gbatemp.net/threads/tesla-the-nintendo-switch-overlay-menu.557362/

**Comment by averne** [comment]
I'm not a fan of this idea, because it means possibly accessing the save possibly while the game is writing to it, which could entail corruption.

**Comment by NWPlayer123** [comment]
If you reverse engineered the game, you could just read a memory address but k
