### ISSUE TITLE
Save outdated

### ISSUE THREAD

**Issue by strikeru97** [averne/Turnips#16]
Hello,
Very nice good App. Since last Update it tells save outdated but saved 5 minutes ago.
Can you please fix?

**Comment by samuelkf** [comment]
I have the same issue. It stopped reading the save on an older version yesterday (I think this was 1.4.1), so I updated to 1.5.1 this morning, but the issue persists.

**Comment by dionvl** [comment]
@strikeru97 @samuelkf update to turnips 1.5.2

**Comment by strikeru97** [comment]
Sorry my fault. The Homebrew shop lists 1.5.1 instead of 1.5.2 ... Updated over FTP from here now works fine.
