### ISSUE TITLE
[Request] Highlight Current Day/Price

### ISSUE THREAD

**Issue by 16BitWonder** [averne/Turnips#2]
Not too big of a deal if this doesn't make it in, but I thought it would be a nice QoL improvement.
Highlight the current day/price in a contrasting color for easy visibility.

And if possible add a point to the graph showing where the user is in the week.
(I recall you mentioning the graphing is a tad restrictive, so no worries if this is out of scope)

Example:
![68747470733a2f2f692e696d6775722e636f6d2f336d4f63785a4e2e6a7067](https://user-images.githubusercontent.com/25729145/80037469-9f09de00-84c1-11ea-96f9-0e860d291577.jpg)

**Comment by averne** [comment]
Nice idea, I'll work on it (will probably add min and max highlighting as well). However I don't think the graph thing is easily doable.

**Comment by duckyb** [comment]
Also why show sunday? It's just always zero

**Comment by averne** [comment]
![2020042313464600-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/45773016/80097174-252e2f00-856b-11ea-83d6-4cea8d82abb3.jpg)
I also hid Sunday as suggested by @duckyb with 3fb7c6b9991e38ebad46993ab2a5d49ec1660ee6
