### ISSUE TITLE
Translation to Spanish

### ISSUE THREAD

**Issue by DRAGONBLUEE144** [averne/Turnips#22]
Hello, I want to contribute with the translation of the application into Spanish.

**Comment by averne** [comment]
Thanks for your interest, could you please translate this json? 
https://github.com/averne/Turnips/blob/master/res/lang/en.json

**Comment by ROYSO72** [comment]
I am also interested in having the Spanish language in the program.  If I can help, I will be happy to do so.

**Comment by averne** [comment]
Please translate the json above and I'll integrate it in the app.

**Comment by ROYSO72** [comment]
Done¡¡¡ I send you a pull request from my fork

**Comment by ROYSO72** [comment]
Hi friend.
When will you create the release with the Spanish language? Thank you.

**Comment by averne** [comment]
Most probably I will make a new release whenever another update drops. If you'd like to use the Spanish translation right away, you can download the nightly build here:
https://github.com/averne/Turnips/suites/998443410/artifacts/12891709

**Comment by ROYSO72** [comment]
Great¡¡

Thanks¡¡
