### ISSUE TITLE
1.6.0

### ISSUE THREAD

**Issue by SoupD** [averne/Turnips#33]
Update 1.6.0, I hope the author will update it. Thank you

**Comment by SoupD** [comment]
[ch.zip](https://github.com/averne/Turnips/files/5572143/ch.zip)
Translated ch.JSON and hope you can add it for me. Thanks! !

**Comment by iomintz** [comment]
You can update the ch.json by finding the file in the github repo, clicking edit, then pasting in the contents of it.

**Comment by averne** [comment]
@SoupD We already have Chinese translations (see [here](https://github.com/averne/Turnips/blob/master/res/lang/ch.json)), could you be more specific about what you changed, such as additions/corrections?
I'll update for 1.6.0 this evening (in a few hours for me).

**Comment by SoupD** [comment]
> @SoupD We already have Chinese translations (see [here](https://github.com/averne/Turnips/blob/master/res/lang/ch.json)), could you be more specific about what you changed, such as additions/corrections?
> I'll update for 1.6.0 this evening (in a few hours for me).

"npcs": {
        "none":           "毫不",
        "gulliver":       "吕游",
        "label":          "绵儿",
        "saharah":        "骆岚",
        "wisp":           "幽幽",
        "celeste":        "傅珂",
        "mabel":          "绢儿",
        "cj":             "俞司廷",
        "flick":          "龙克斯",
        "kicks":          "薛革",
        "leif":           "然然",
        "redd":           "狐利",
        "gullivarrr":     "海盗"
Thank you, if you can’t change it, don’t change it, and wish you a good day again

**Comment by averne** [comment]
Thanks, I added your updated translation

**Comment by SoupD** [comment]
> Thanks, I added your updated translation

Sorry to interrupt you, why does some Chinese show the question mark

**Comment by iomintz** [comment]
https://github.com/averne/Turnips/commit/d89cc2b1935e84ad0ebdc10d500aa30b05c66eb6 if you're talking about this commit, I don't see any.

**Comment by averne** [comment]
Sorry, this was caused by uncommon characters that weren't included in the font atlas. Should be fixed in 6e4cd6d.
