### ISSUE TITLE
Save outdated

### ISSUE THREAD

**Issue by Bruxes** [averne/Turnips#36]
It says my last save time was 04-12-2020 Save outdated!
But I've been saving the game and still doesn't work.

**Comment by Bruxes** [comment]
I'm using latest version 1.6.7

**Comment by Conan179** [comment]
@Bruxes ´the last version is 1.7.0

**Comment by Bruxes** [comment]
> 
> 
> @Bruxes ´the last version is 1.7.0

the last version of the app is 1.6.7, yes I'm using last version of the game which is in fact 1.7.0

**Comment by Conan179** [comment]
@Bruxes I'm sorry. I misunderstood your question, sorry.

**Comment by Garonne** [comment]
You last saved on december 4th?
The app probably can't read your current weeks turnip prices since your save is older than last Sunday (That's what it means by "outdated"). Your last save is prior to current sunday.

**Comment by averne** [comment]
Could you dump your save with this https://github.com/J-D-K/JKSV and upload it?
