### ISSUE TITLE
Docked mode has wrong offsets

### ISSUE THREAD

**Issue by duckyb** [averne/Turnips#5]
While using docked mode the table and the backound are off-centered

![2020042800015700-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/27895007/80425330-b8f15980-88e3-11ea-9cfb-f643cb4b11b8.jpg)

**Comment by uaevuon** [comment]
Same on mine.
Both on 720p and 1080p, it looks like this.

**Comment by duckyb** [comment]
Awesome, thank you for the fix

**Comment by celynwalters** [comment]
There's a similar minor issue on `v1.4.0` (after the above fix).
The interface needs to be rescaled when switching between handheld/docked with the app already open.

Handheld -> docked:
![2020042822403700-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/3299161/80540837-f9afa800-89a1-11ea-84a8-fecad4c52054.jpg)

Docked -> handheld:
![2020042822440300-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/3299161/80540841-fc120200-89a1-11ea-9185-11e76a902d4a.jpg)

Thanks a lot!
