### ISSUE TITLE
Incorrect pricing

### ISSUE THREAD

**Issue by dlee79** [averne/Turnips#6]
[8000000000000000.zip](https://github.com/averne/Turnips/files/4542223/8000000000000000.zip)

**Comment by averne** [comment]
This file is encrypted with console-specific keys, I canot open it. Can you dump with [JKSV](https://github.com/J-D-K/JKSV)? See in the "Device saves" section. I will need the files "mainHeader.dat" and "main.dat".
Please also tell me which value(s) (day, AM/PM) is(are) wrong.
I would also like more info on your setup (game version, CFW/CFW version, emunand/sysnand).

**Comment by dlee79** [comment]
Ahh okay, sorry. Will do as soon as I can

**Comment by dlee79** [comment]
[Device Saves - 2020.04.28 @ 00.16.18.zip](https://github.com/averne/Turnips/files/4543317/Device.Saves.-.2020.04.28.%40.00.16.18.zip)

Hi, attached are the mainHeader and main.dat files. I just downloaded Turnips today, so I was only able to look for Monday PM. Turnips in-store were selling for 82. I bought turnips on Sunday for 98

Game version is 1.2
CFW version is AMS 0.10.5

**Comment by averne** [comment]
Something seems wrong with your save. Manually checking the prices, I see the buy price should be 0x66 = 102 bells, Monday PM 0x3B = 59, etc
![save](https://user-images.githubusercontent.com/45773016/80477533-5f714500-894c-11ea-8dea-0449fb25258b.png)
I've tried opening with [NHSE](https://github.com/kwsch/NHSE/), but it fails somewhere.
![Sans titre](https://user-images.githubusercontent.com/45773016/80477867-f6d69800-894c-11ea-834c-14ceb798ce11.png)
One last thing, the version indicated by mainHeader.dat is 1.1.3, not 1.2.0.
Did you somehow mess with game versions? Do you have an emunand setup?

**Comment by dlee79** [comment]
Strange, I didn't mess with game versions at all. I have emunand set up for homebrew stuff and I just use the basic sysnand for legit games

**Comment by averne** [comment]
Yeah it's pretty weird indeed, and honestly figuring this is out of my reach. The prices I'm reading manually match the ones found by my code.
Have you tried opening your save with  [NHSE](https://github.com/kwsch/NHSE/) (dl [here](https://dev.azure.com/project-pokemon/NHSE/_build/results?buildId=1511&view=artifacts&type=publishedArtifacts))? If that doesn't work, you can try posting an issue on their tracker, where you will find people more experienced with the save format.

**Comment by Leighmond** [comment]
I actually have the exact same issue, and get the same error in NHSE.
I play the game on sysNAND and then restore to emuNAND which it sounds like is the same as OP.

Game version 1.2, CFW: Atmosphere 0.12.0

**Comment by averne** [comment]
Indeed. I've had a similar issue happening to me last week, where store prices didn't exactly match save prices. However, quitting and relaunching the game fixed it. 
Could you try that?

**Comment by Leighmond** [comment]
Yes that does seem to solve the problem.
It seems that when I transfer from sysNAND to emuNAND I then need to go in and let the game save so that it stores the prices correctly.

**Comment by averne** [comment]
Cool, I'll mark this as solved. 
For the record the mismatch doesn't even need emunand tricks to appear, since I don't use it. I'm not sure what triggered it for me, maybe hosting other players.
