### ISSUE TITLE
[Suggestion] Change highlighted cells

### ISSUE THREAD

**Issue by duckyb** [averne/Turnips#7]
I think that highlighting the lowest cell is pretty useless, I would also remove the highlighting of the current value but that's debatable.

Instead, I would suggest to only highlight the day of the week and the am/pm value corresponding to the max value, for example:

![example](https://user-images.githubusercontent.com/27895007/80426199-88aaba80-88e5-11ea-83af-7901cd50fd81.png)
 
In this case, highlight only the values in the orange box

**Comment by duckyb** [comment]
Maybe you could also add a dynamic text suggestion, like:

> You should sell your turnips on Monday morning!

or 

> You should sell your turnips on Wednesday evening, we will offer 141 bells!

**Comment by averne** [comment]
I'm not a huge fan of either tbh, to me it seems that would only add clutter. Max day/hour are already visible at a glance.
