### ISSUE TITLE
Missing interface rescaling

### ISSUE THREAD

**Issue by duckyb** [averne/Turnips#8]
There's a similar minor issue on `v1.4.0` (after the above fix).
The interface needs to be rescaled when switching between handheld/docked with the app already open.

Handheld -> docked:
![2020042822403700-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/3299161/80540837-f9afa800-89a1-11ea-84a8-fecad4c52054.jpg)

Docked -> handheld:
![2020042822440300-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/3299161/80540841-fc120200-89a1-11ea-9185-11e76a902d4a.jpg)

Thanks a lot!

_Originally posted by @celynwalters in https://github.com/averne/Turnips/issues/5#issuecomment-620873555_

**Comment by averne** [comment]
Yeah I saw that, I've done some work on it but I need to play further with imgui to get it right.

**Comment by duckyb** [comment]
Ok, I just wanted to put it in it's own thread

**Comment by averne** [comment]
Fixed along with the switch to the deko3d graphics backend (769d312).
