### ISSUE TITLE
When did the prices change?

### ISSUE THREAD

**Issue by Bart1909** [averne/Turnips#9]
Hi,

first: Great Tool!

But I want to ask, if you know, when the prices change?
Last Sunday, the tool said, that I can buy for 100 (which was the correct price) and sell with a max value on saturday with 188.
On Monday, the tool changed the values and said, the buying price is 101 and my max value is thursday with 161. The values were correct the whole week.
Now, this Sunday, the values changed again. Now, it says, the buy price is 106 (which is correct again) and my max value should be 444 on friday. 
Will this change again tomorrow (on Monday)?

**Comment by averne** [comment]
Prices change on SUndays upon buying Turnips.
They can also change when time travelling. Have they changed today as well?

**Comment by Bart1909** [comment]
No, today they didn't change, and everything seems fine

**Comment by averne** [comment]
Good. It's possible you checked the prices two weeks ago *before* buying turnips, and in this case the save had not been updated yet. You were then prompted prices for the previous week.

**Comment by Bart1909** [comment]
This could be the reason. Don't know.

I will have a look and if the prices are incorrect or something else, I will re-open this ticket.

Thanks for the support :)

**Comment by duckyb** [comment]
Every time you travel back in time (even for just 1 minute) the prices of the entire week are re-rolled
